#--- develop
name: Action_Test2
env:
  APPLICATION_NAME : "MyAPP"
  PACKAGE_NAME     : "MyPackage_ver_${{ github.sha }}"
  

#--- далее указываем реагировать только на push для ветки master
on:
  push:
    branches: 
      - master

jobs:
  testing1:
#--- запускаем на машине ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Step1 Echo test
      run: echo "Hello, testing step 1 !"

    - name: Step2 
      run: |
        echo "Testing,"
        echo "Application Name: ${{ env.APPLICATION_NAME }} "
        echo "Package Name : ${{ env.PACKAGE_NAME }} "

    - name: Show folder list files
      run : ls -la

    - name: Git clone my repo to folder
      uses: actions/checkout@v1

  deploy:
    runs-on: ubuntu-latest
    needs: [testing1]

    steps:
    - name: Step1 Dev Echo test
      run: |
        echo "Development,"
        echo "Application Name: ${{ env.APPLICATION_NAME }} "
        echo "Package Name : ${{ env.PACKAGE_NAME }} "

    - name: Git clone my repo to folder
      uses: actions/checkout@v1

    - name: Show folder list files
      run : ls -la
