name: ActionTest1

on: [push]

jobs:
  build:
    name: Build1
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 clone repo
    - uses: actions/checkout@v1
      run: echo Hello, world! Step 1 completed

    - name: Step2 !
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.