name: ActionTest1

on: [push]

jobs:
  build:
    name: Build1
    runs-on: ubuntu-latest

    steps:
    - name: Шаг 1 запуск клонирования репозитория на инстансе
    - uses: actions/checkout@v1
      run: echo Hello, world! Шаг 1 выполнен

    - name: Шаг 2 
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
